# fly.toml app configuration file generated for ez-jobs-aged-leaf-1768 on 2025-08-07T15:18:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ez-jobs-aged-leaf-1768'
primary_region = 'sjc'

[processes]
app = "python3 scheduler.py"

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
